In [76]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [77]:
#Loading Datasets
d1=pd.read_csv(r"C:\Users\malak\Downloads\artist.csv")
d2=pd.read_csv(r"C:\Users\malak\Downloads\canvas_size.csv")
d3=pd.read_csv(r"C:\Users\malak\Downloads\museum.csv")
d4=pd.read_csv(r"C:\Users\malak\Downloads\museum_hours.csv")
d5=pd.read_csv(r"C:\Users\malak\Downloads\product_size.csv")
d6=pd.read_csv(r"C:\Users\malak\Downloads\subject.csv")
d7=pd.read_csv(r"C:\Users\malak\Downloads\work.csv")
d8=pd.read_csv(r"C:\Users\malak\Downloads\image_link.csv")

In [78]:
d1

,artist_id,full_name,first_name,middle_names,last_name,nationality,style,birth,death
0,500,Pierre-Auguste Renoir,Pierre,Auguste,Renoir,French,Impressionist,1841,1919
1,501,Alexandre Cabanel,Alexandre,NaN,Cabanel,French,Classicist,1823,1889
2,502,James Ensor,James,NaN,Ensor,Belgian,Expressionist,1860,1949
3,503,Maximilien Luce,Maximilien,NaN,Luce,French,Pointillist,1858,1941
4,504,August Macke,August,NaN,Macke,German,Expressionist,1887,1914
...,...,...,...,...,...,...,...,...,...
416,916,Jean-Baptiste-Camille Corot,Jean,Baptiste Camille,Corot,French,Romantic,1796,1875
417,917,Jan Toorop,Jan,NaN,Toorop,Dutch,Symbolist,1858,1928
418,918,Rembrandt Peale,Rembrandt,NaN,Peale,American,Neoclassical,1778,1860
419,919,Edmund Charles Tarbell,Edmund,Charles,Tarbell,American,Impressionist,1862,1938
420,920,Rembrandt Van Rijn,Rembrandt,NaN,Van Rijn,Dutch,Baroque,1606,1669

In [79]:
d2

     size_id  width  height                       label
0         20     20     NaN               20" Long Edge
1         24     24     NaN               24" Long Edge
2         30     30     NaN               30" Long Edge
3         36     36     NaN               36" Long Edge
4         40     40     NaN               40" Long Edge
..       ...    ...     ...                         ...
195     7963     79    63.0  79" x 63"(201 cm x 160 cm)
196     8040     80    40.0  80" x 40"(203 cm x 102 cm)
197     8051     80    51.0  80" x 51"(203 cm x 130 cm)
198     8959     89    59.0  89" x 59"(226 cm x 150 cm)
199     9648     96    48.0  96" x 48"(244 cm x 122 cm)

[200 rows x 4 columns]

In [80]:
d3

,museum_id,name,address,city,state,postal,country,phone,url
0,30,The Museum of Modern Art,11 W 53rd St,New York,NY,10019,USA,+1 212 708-9400,https://www.moma.org/
1,31,Pushkin State Museum of Fine Arts,12 Ulitsa Volkhonka,Moscow,NaN,119019,Russia,+7 495 697-95-78,https://pushkinmuseum.art/
2,32,National Gallery of Victoria,180 St Kilda Rd,Melbourne,Victoria,3004,Australia,+61 (0)3 8620 2222,https://www.ngv.vic.gov.au/
3,33,São Paulo Museum of Art,"Av. Paulista, 1578 - Bela Vista",São Paulo,NaN,01310-200,Brazil,+55 11 3149-5959,https://masp.org.br/
4,34,The State Hermitage Museum,Palace Square,2,Sankt-Peterburg,190000,Russia,7 812 710-90-79,https://www.hermitagemuseum.org/wps/portal/her...
5,35,The Metropolitan Museum of Art,1000 5th Ave,New York,NY,10028,USA,+1 212 535-7710,https://www.metmuseum.org/
6,36,Museum Folkwang,Museumsplatz 1,45128,Essen,NaN,Germany,49 201 8845000,https://www.museum-folkwang.de/en
7,37,Museum of Grenoble,5 Pl. de Lavalette,38000,Grenoble,NaN,France,33 4 76 63 44 44,https://www.museedegrenoble.fr/1986-the-museum...
8,38,Musée des Beaux-Arts de Quimper,40 Pl. Saint-Corentin,29000,Quimper,NaN,France,33 2 98 95 45 20,https://www.mbaq.fr/en/home-3.html
9,39,Nelson-Atkins Museum of Art,4525 Oak St,Kansas City,MO,64111,USA,+1 816 751-1278,https://www.nelson-atkins.org/
10,40,Musée du Louvre,Rue de Rivoli,75001,Paris,NaN,France,33 1 40 20 50 50,https://www.louvre.fr/en
11,41,National Maritime Museum,Romney Rd,London,SE10 9NF,NaN,United Kingdom,44 20 8858 4422,https://www.rmg.co.uk/national-maritime-museum
12,42,Museum of Fine Arts Boston,465 Huntington Ave,Boston,MA,2115,USA,617-267-9300,https://www.mfa.org/
13,43,Rijksmuseum,Museumstraat 1,Amsterdam,NaN,1071 XX,Netherlands,31 20 674 7000,https://www.rijksmuseum.nl/en/visit
14,44,Israel Museum,Derech Ruppin 11,Jerusalem,NaN,NaN,Israel,972 2-670-8811,https://www.imj.org.il/en
15,45,Kunsthaus Zürich,Heimplatz 1,Zurich,NaN,8001,Switzerland,+41 44 253 84 84,https://www.kunsthaus.ch/en/
16,46,National Gallery of Art,Constitution Ave. NW,Washington,DC,20565,USA,+1 202 737-4215,https://www.nga.gov/
17,47,National Gallery,Trafalgar Square,London,England,WC2N 5DN,UK,+44 (0)20 7747 2885,https://www.nationalgallery.org.uk/
18,48,Mauritshuis Museum,Plein 29,Den Haag,NaN,2511,Netherlands,+31 70 302 3456,https://www.mauritshuis.nl/en/
19,49,Musée d'Orsay,1 Rue de la Légion d'Honneur,Paris,NaN,75007,France,+33 (0)1 40 49 48 14,https://www.musee-orsay.fr/en
20,50,The Prado Museum,"C. de Ruiz de Alarcón, 23",Madrid,NaN,28014,Spain,+34 913 30 28 00,https://www.museodelprado.es/en
21,51,The Barnes Foundation,2025 Benjamin Franklin Pkwy,Philadelphia,PA,19130,USA,+1 215 278-7000,https://www.barnesfoundation.org/
22,52,Hungarian National Gallery,Szent György tér 2,Budapest,NaN,1014,Hungary,+36 20 439 7331,https://en.mng.hu/
23,53,Cleveland Museum Of Art,11150 East Blvd,Cleveland,OH,44106,USA,+1 216 421-7350,http://clevelandart.org/
24,54,"Museum of Fine Arts, Houston",1001 Bissonnet St,Houston,TX,77005,USA,+1 713 639-7300,https://www.mfah.org/
25,55,The J. Paul Getty Museum,1200 Getty Center Dr,Los Angeles,CA,90049,USA,+1 310 440-7300,https://www.getty.edu/museum/
26,56,Thussen-Bornemisza Museum,"P.º del Prado, 8",Madrid,NaN,28014,Spain,+ 34 917 91 13 70,https://www.museothyssen.org/en
27,57,Van Gogh Museum,Museumplein 6,Amsterdam,NaN,1071 DJ,Netherlands,+1 020 570 52 00,https://www.vangoghmuseum.nl/en
28,58,The Phillips Collection,1600 21st St NW,Washington,DC,20009,USA,+1 202 387-2151,https://www.phillipscollection.org/
29,59,Toledo Museum of Art,2445 Monroe St,Toledo,OH,43620,USA,+1 419 255-8000,https://www.toledomuseum.org/
30,60,Los Angeles County Museum of Art,5905 Wilshire Blvd,Los Angeles,CA,90036,USA,+1 323 857-6000,https://www.lacma.org/
31,61,Solomon R. Guggenheim Museum,1071 Fifth Avenue,New York,NY,10128,USA,+1 212 423-3500,https://www.guggenheim.org/
32,62,The Tate Gallery,Millbank,London,England,SW1P 4RG,UK,+44 (0)20 7887 8888,https://www.tate.org.uk/visit/tate-britain
33,63,Indianapolis Museum of Art,4000 N Michigan Rd,Indianapolis,IN,46208,USA,+1 317923-1331,https://discovernewfields.org/
34,64,Museum of Fine Arts of Nancy,3 Pl. Stanislas,Nancy,NaN,54000,France,+33 3 83 85 30 01,https://useum.org/museum/Museum-of-Fine-Arts-o...
35,65,Fine Arts Museums of San Francisco Legion of H...,100 34th Avenue,San Francisco,CA,94121,USA,+1 415 750-3600,https://www.famsf.org/
36,66,Smithsonian American Art Museum,800 G Street NW,Washington,DC,20004,USA,+1 202 633-1000,https://americanart.si.edu/
37,67,Philadelphia Museum of Art,2600 Benjamin Franklin Pkwy,Philadelphia,PA,19130,USA,+1 215 763-8100,https://philamuseum.org/
38,68,The Art Institute of Chicago,111 S Michigan Ave,Chicago,IL,60603,USA,+1 312 443-3600,https://www.artic.edu/
39,69,Saint Louis Art Museum,1 Fine Arts Dr,St. Louis,MO,63001,USA,+1 304 721-0072,http://www.slam.org/
40,70,Uffizi Gallery Italy,"Piazzale degli Uffizi, 6",Firenze,FL,50122,Italy,+39 055 294883,https://www.uffizi.it/en
41,71,Ohara Museum of Art,1 Chome-1-15 Central,Kurashiki,Okayama,710-8575,Japan,+81 86-422-0005,https://www.ohara.or.jp/en/
42,72,Musée Marmottan Monet,2 Rue Louis Boilly,Paris,NaN,75016,France,+33 1 44 96 50 33,https://www.marmottan.fr/en/
43,73,Walters Art Museum,600 N Charles St,Baltimore,MD,21201,USA,+1 410 547-9000,https://thewalters.org/
44,74,Kröller-Müller Museum,Houtkampweg 6,6731 AW Otterlo,NaN,NaN,Netherlands,+31 318 591 241,https://krollermuller.nl/en
45,75,National Museum,Cathays Park,Cardiff,Wales,CF10 3NP,UK,+44 300 111 2333,https://museum.wales/
46,76,Columbus Museum of Art,480 E Broad St,Columbus,OH,43215,USA,+1 (614) 221-6801,https://www.columbusmuseum.org/
47,77,Kimbell Art Museum,3333 Camp Bowie Blvd,Fort Worth,TX,76107,USA,+(817) 332-8451,https://kimbellart.org/
48,78,Walker Art Gallery,William Brown St,Liverpool,NaN,L3 8EL,UK,+44 151 478 4199,https://www.liverpoolmuseums.org.uk/
49,79,National Museum of Art Architecture and Design,Brynjulf Bulls plass 3,Oslo,NaN,0250,Norway,+47 21 98 20 00,https://www.nasjonalmuseet.no/en/
50,80,Dallas Museum of Art,1717 N Harwood St,Dallas,TX,75201,USA,+1(214) 922-1200,https://www.dma.org/
51,81,Museum of Fine Arts,Hodlerstrasse 8,Bern,NaN,3011,Switzerland,+41 31 328 09 44,https://www.kunstmuseumbern.ch/en/
52,82,Army Museum,129 Rue de Grenelle,Paris,NaN,75007,France,+33 810 11 33 99,https://www.musee-armee.fr/en/english-version....
53,83,Chrysler Museum of Art,1 Memorial Pl,Norfolk,VA,23510,USA,+1(757) 664-6200,https://chrysler.org/
54,84,National Gallery Prague,Václavské nám. 68,Nové Měst,NaN,110 15,Czechia,+420 224 497 111,https://www.nm.cz/en
55,85,Norton Simon Museum,411 W Colorado Blvd,Pasadena,CA,91105,USA,+1(626) 449-6840,https://www.nortonsimon.org/
56,86,Courtauld Gallery,Somerset House,Stran,London,WC2R 0RN,UK,+44 20 3947 7777,https://courtauld.ac.uk/

In [81]:
d4

     museum_id        day      open     close
0           30     Sunday  10:30:AM  05:30:PM
1           30     Monday  10:30:AM  05:30:PM
2           30    Tuesday  10:30:AM  05:30:PM
3           30  Wednesday  10:30:AM  05:30:PM
4           30    Thusday  10:30:AM  05:30:PM
..         ...        ...       ...       ...
346         86    Tuesday  10:00:AM  06:00:PM
347         86  Wednesday  10:00:AM  06:00:PM
348         86   Thursday  10:00:AM  06:00:PM
349         86     Friday  10:00:AM  06:00:PM
350         86   Saturday  10:00:AM  06:00:PM

[351 rows x 4 columns]

In [82]:
d5

        work_id size_id  sale_price  regular_price
0        160228      24          85             85
1        160228      30          95             95
2        160236      24          85             85
3        160236      30          95             95
4        160244      24          85             85
...         ...     ...         ...            ...
110342   184829    3030         335            595
110343   184829    3636         395            715
110344   184829    4040         455            835
110345   184829    4848         565           1055
110346   184829    6060         775           1475

[110347 rows x 4 columns]

In [83]:
d6

      work_id       subject
0      160228    Still-Life
1      160236    Still-Life
2      160244    Still-Life
3      160252    Still-Life
4      160260    Still-Life
...       ...           ...
6766     8145     Portraits
6767     8171  Rivers/Lakes
6768     8179        Summer
6769     8183     Seascapes
6770     8269     Seascapes

[6771 rows x 2 columns]

In [84]:
d7

,work_id,name,artist_id,style,museum_id
0,160228,Still Life with Flowers and a Watch,615,Baroque,43.0
1,160236,Still Life with Fruit and a Beaker on a Cock's...,615,Baroque,43.0
2,160244,Still Life with Fruit and a Goldfinch,615,Baroque,43.0
3,160252,Still Life with Fruit and Oysters,615,Baroque,43.0
4,160260,"Still Life with Fruit, Oysters, and a Porcelai...",615,Baroque,43.0
...,...,...,...,...,...
14771,8279,Weaning the Calf,794,American Art,35.0
14772,8283,"West Point, Prout's Neck",794,American Art,NaN
14773,8285,Winding Line,794,American Art,NaN
14774,184820,Untitled,620,Surrealism,NaN
14775,184829,Untitled,620,Surrealism,NaN

In [85]:
d8

,work_id,url,thumbnail_small_url,thumbnail_large_url
0,181978,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
1,173188,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
2,194065,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
3,129337,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
4,141073,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
...,...,...,...,...
14770,194297,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
14771,182986,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
14772,1477,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
14773,28147,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
14774,29316,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...

In [86]:
d7

,work_id,name,artist_id,style,museum_id
0,160228,Still Life with Flowers and a Watch,615,Baroque,43.0
1,160236,Still Life with Fruit and a Beaker on a Cock's...,615,Baroque,43.0
2,160244,Still Life with Fruit and a Goldfinch,615,Baroque,43.0
3,160252,Still Life with Fruit and Oysters,615,Baroque,43.0
4,160260,"Still Life with Fruit, Oysters, and a Porcelai...",615,Baroque,43.0
...,...,...,...,...,...
14771,8279,Weaning the Calf,794,American Art,35.0
14772,8283,"West Point, Prout's Neck",794,American Art,NaN
14773,8285,Winding Line,794,American Art,NaN
14774,184820,Untitled,620,Surrealism,NaN
14775,184829,Untitled,620,Surrealism,NaN

In [87]:
#1. Fetch all the paintings which are not displayed on any museums?
#Where the museum id will be Null that are the paintings which are not displayed in museum
paintings_not_in_museums = d7[d7['museum_id'].isnull()]

In [88]:
paintings_not_in_museums

,work_id,name,artist_id,style,museum_id
6,125752,Arabian Horses at Pasture,757,Baroque,NaN
7,125818,Count Halm on His Basedow Estate,757,Baroque,NaN
9,125763,Napoleon Before the Burning City of Smolensk,757,Baroque,NaN
10,125774,Peasants Resting in the Field,757,Baroque,NaN
11,125785,Portrait Oberleutnant Theodor Von Klein,757,Baroque,NaN
...,...,...,...,...,...
14768,8273,Waiting for an Answer,794,American Art,NaN
14772,8283,"West Point, Prout's Neck",794,American Art,NaN
14773,8285,Winding Line,794,American Art,NaN
14774,184820,Untitled,620,Surrealism,NaN
14775,184829,Untitled,620,Surrealism,NaN

In [89]:
d7

,work_id,name,artist_id,style,museum_id
0,160228,Still Life with Flowers and a Watch,615,Baroque,43.0
1,160236,Still Life with Fruit and a Beaker on a Cock's...,615,Baroque,43.0
2,160244,Still Life with Fruit and a Goldfinch,615,Baroque,43.0
3,160252,Still Life with Fruit and Oysters,615,Baroque,43.0
4,160260,"Still Life with Fruit, Oysters, and a Porcelai...",615,Baroque,43.0
...,...,...,...,...,...
14771,8279,Weaning the Calf,794,American Art,35.0
14772,8283,"West Point, Prout's Neck",794,American Art,NaN
14773,8285,Winding Line,794,American Art,NaN
14774,184820,Untitled,620,Surrealism,NaN
14775,184829,Untitled,620,Surrealism,NaN

In [90]:
# 2. Are there museums without any paintings?
#Here we will check for Museum and Work datasetto check answer of this question so we check for combined dataset
museums_without_paintings = d3[d3['museum_id'].isin(d7['museum_id'].dropna())]

In [91]:
museums_without_paintings

,museum_id,name,address,city,state,postal,country,phone,url
0,30,The Museum of Modern Art,11 W 53rd St,New York,NY,10019,USA,+1 212 708-9400,https://www.moma.org/
1,31,Pushkin State Museum of Fine Arts,12 Ulitsa Volkhonka,Moscow,NaN,119019,Russia,+7 495 697-95-78,https://pushkinmuseum.art/
2,32,National Gallery of Victoria,180 St Kilda Rd,Melbourne,Victoria,3004,Australia,+61 (0)3 8620 2222,https://www.ngv.vic.gov.au/
3,33,São Paulo Museum of Art,"Av. Paulista, 1578 - Bela Vista",São Paulo,NaN,01310-200,Brazil,+55 11 3149-5959,https://masp.org.br/
4,34,The State Hermitage Museum,Palace Square,2,Sankt-Peterburg,190000,Russia,7 812 710-90-79,https://www.hermitagemuseum.org/wps/portal/her...
5,35,The Metropolitan Museum of Art,1000 5th Ave,New York,NY,10028,USA,+1 212 535-7710,https://www.metmuseum.org/
6,36,Museum Folkwang,Museumsplatz 1,45128,Essen,NaN,Germany,49 201 8845000,https://www.museum-folkwang.de/en
7,37,Museum of Grenoble,5 Pl. de Lavalette,38000,Grenoble,NaN,France,33 4 76 63 44 44,https://www.museedegrenoble.fr/1986-the-museum...
8,38,Musée des Beaux-Arts de Quimper,40 Pl. Saint-Corentin,29000,Quimper,NaN,France,33 2 98 95 45 20,https://www.mbaq.fr/en/home-3.html
9,39,Nelson-Atkins Museum of Art,4525 Oak St,Kansas City,MO,64111,USA,+1 816 751-1278,https://www.nelson-atkins.org/
10,40,Musée du Louvre,Rue de Rivoli,75001,Paris,NaN,France,33 1 40 20 50 50,https://www.louvre.fr/en
11,41,National Maritime Museum,Romney Rd,London,SE10 9NF,NaN,United Kingdom,44 20 8858 4422,https://www.rmg.co.uk/national-maritime-museum
12,42,Museum of Fine Arts Boston,465 Huntington Ave,Boston,MA,2115,USA,617-267-9300,https://www.mfa.org/
13,43,Rijksmuseum,Museumstraat 1,Amsterdam,NaN,1071 XX,Netherlands,31 20 674 7000,https://www.rijksmuseum.nl/en/visit
14,44,Israel Museum,Derech Ruppin 11,Jerusalem,NaN,NaN,Israel,972 2-670-8811,https://www.imj.org.il/en
15,45,Kunsthaus Zürich,Heimplatz 1,Zurich,NaN,8001,Switzerland,+41 44 253 84 84,https://www.kunsthaus.ch/en/
16,46,National Gallery of Art,Constitution Ave. NW,Washington,DC,20565,USA,+1 202 737-4215,https://www.nga.gov/
17,47,National Gallery,Trafalgar Square,London,England,WC2N 5DN,UK,+44 (0)20 7747 2885,https://www.nationalgallery.org.uk/
18,48,Mauritshuis Museum,Plein 29,Den Haag,NaN,2511,Netherlands,+31 70 302 3456,https://www.mauritshuis.nl/en/
19,49,Musée d'Orsay,1 Rue de la Légion d'Honneur,Paris,NaN,75007,France,+33 (0)1 40 49 48 14,https://www.musee-orsay.fr/en
20,50,The Prado Museum,"C. de Ruiz de Alarcón, 23",Madrid,NaN,28014,Spain,+34 913 30 28 00,https://www.museodelprado.es/en
21,51,The Barnes Foundation,2025 Benjamin Franklin Pkwy,Philadelphia,PA,19130,USA,+1 215 278-7000,https://www.barnesfoundation.org/
22,52,Hungarian National Gallery,Szent György tér 2,Budapest,NaN,1014,Hungary,+36 20 439 7331,https://en.mng.hu/
23,53,Cleveland Museum Of Art,11150 East Blvd,Cleveland,OH,44106,USA,+1 216 421-7350,http://clevelandart.org/
24,54,"Museum of Fine Arts, Houston",1001 Bissonnet St,Houston,TX,77005,USA,+1 713 639-7300,https://www.mfah.org/
25,55,The J. Paul Getty Museum,1200 Getty Center Dr,Los Angeles,CA,90049,USA,+1 310 440-7300,https://www.getty.edu/museum/
26,56,Thussen-Bornemisza Museum,"P.º del Prado, 8",Madrid,NaN,28014,Spain,+ 34 917 91 13 70,https://www.museothyssen.org/en
27,57,Van Gogh Museum,Museumplein 6,Amsterdam,NaN,1071 DJ,Netherlands,+1 020 570 52 00,https://www.vangoghmuseum.nl/en
28,58,The Phillips Collection,1600 21st St NW,Washington,DC,20009,USA,+1 202 387-2151,https://www.phillipscollection.org/
29,59,Toledo Museum of Art,2445 Monroe St,Toledo,OH,43620,USA,+1 419 255-8000,https://www.toledomuseum.org/
30,60,Los Angeles County Museum of Art,5905 Wilshire Blvd,Los Angeles,CA,90036,USA,+1 323 857-6000,https://www.lacma.org/
31,61,Solomon R. Guggenheim Museum,1071 Fifth Avenue,New York,NY,10128,USA,+1 212 423-3500,https://www.guggenheim.org/
32,62,The Tate Gallery,Millbank,London,England,SW1P 4RG,UK,+44 (0)20 7887 8888,https://www.tate.org.uk/visit/tate-britain
33,63,Indianapolis Museum of Art,4000 N Michigan Rd,Indianapolis,IN,46208,USA,+1 317923-1331,https://discovernewfields.org/
34,64,Museum of Fine Arts of Nancy,3 Pl. Stanislas,Nancy,NaN,54000,France,+33 3 83 85 30 01,https://useum.org/museum/Museum-of-Fine-Arts-o...
35,65,Fine Arts Museums of San Francisco Legion of H...,100 34th Avenue,San Francisco,CA,94121,USA,+1 415 750-3600,https://www.famsf.org/
36,66,Smithsonian American Art Museum,800 G Street NW,Washington,DC,20004,USA,+1 202 633-1000,https://americanart.si.edu/
37,67,Philadelphia Museum of Art,2600 Benjamin Franklin Pkwy,Philadelphia,PA,19130,USA,+1 215 763-8100,https://philamuseum.org/
38,68,The Art Institute of Chicago,111 S Michigan Ave,Chicago,IL,60603,USA,+1 312 443-3600,https://www.artic.edu/
39,69,Saint Louis Art Museum,1 Fine Arts Dr,St. Louis,MO,63001,USA,+1 304 721-0072,http://www.slam.org/
40,70,Uffizi Gallery Italy,"Piazzale degli Uffizi, 6",Firenze,FL,50122,Italy,+39 055 294883,https://www.uffizi.it/en
41,71,Ohara Museum of Art,1 Chome-1-15 Central,Kurashiki,Okayama,710-8575,Japan,+81 86-422-0005,https://www.ohara.or.jp/en/
42,72,Musée Marmottan Monet,2 Rue Louis Boilly,Paris,NaN,75016,France,+33 1 44 96 50 33,https://www.marmottan.fr/en/
43,73,Walters Art Museum,600 N Charles St,Baltimore,MD,21201,USA,+1 410 547-9000,https://thewalters.org/
44,74,Kröller-Müller Museum,Houtkampweg 6,6731 AW Otterlo,NaN,NaN,Netherlands,+31 318 591 241,https://krollermuller.nl/en
45,75,National Museum,Cathays Park,Cardiff,Wales,CF10 3NP,UK,+44 300 111 2333,https://museum.wales/
46,76,Columbus Museum of Art,480 E Broad St,Columbus,OH,43215,USA,+1 (614) 221-6801,https://www.columbusmuseum.org/
47,77,Kimbell Art Museum,3333 Camp Bowie Blvd,Fort Worth,TX,76107,USA,+(817) 332-8451,https://kimbellart.org/
48,78,Walker Art Gallery,William Brown St,Liverpool,NaN,L3 8EL,UK,+44 151 478 4199,https://www.liverpoolmuseums.org.uk/
49,79,National Museum of Art Architecture and Design,Brynjulf Bulls plass 3,Oslo,NaN,0250,Norway,+47 21 98 20 00,https://www.nasjonalmuseet.no/en/
50,80,Dallas Museum of Art,1717 N Harwood St,Dallas,TX,75201,USA,+1(214) 922-1200,https://www.dma.org/
51,81,Museum of Fine Arts,Hodlerstrasse 8,Bern,NaN,3011,Switzerland,+41 31 328 09 44,https://www.kunstmuseumbern.ch/en/
52,82,Army Museum,129 Rue de Grenelle,Paris,NaN,75007,France,+33 810 11 33 99,https://www.musee-armee.fr/en/english-version....
53,83,Chrysler Museum of Art,1 Memorial Pl,Norfolk,VA,23510,USA,+1(757) 664-6200,https://chrysler.org/
54,84,National Gallery Prague,Václavské nám. 68,Nové Měst,NaN,110 15,Czechia,+420 224 497 111,https://www.nm.cz/en
55,85,Norton Simon Museum,411 W Colorado Blvd,Pasadena,CA,91105,USA,+1(626) 449-6840,https://www.nortonsimon.org/
56,86,Courtauld Gallery,Somerset House,Stran,London,WC2R 0RN,UK,+44 20 3947 7777,https://courtauld.ac.uk/

In [92]:
# 3. How many paintings have an asking price of more than their regular price?
#we already have columns of reg price and sale price justa filter
paintings_higher_price = d5[d5['sale_price'] > d5['regular_price']]

In [93]:
paintings_higher_price

Empty DataFrame
Columns: [work_id, size_id, sale_price, regular_price]
Index: []

In [94]:
d5

        work_id size_id  sale_price  regular_price
0        160228      24          85             85
1        160228      30          95             95
2        160236      24          85             85
3        160236      30          95             95
4        160244      24          85             85
...         ...     ...         ...            ...
110342   184829    3030         335            595
110343   184829    3636         395            715
110344   184829    4040         455            835
110345   184829    4848         565           1055
110346   184829    6060         775           1475

[110347 rows x 4 columns]

In [95]:
# 4. Identify the paintings whose asking price is less than 50% of their regular price(soln:-Just simple math)
paintings_lower_price = d5[d5['sale_price'] < 0.5 * d5['regular_price']]

In [96]:
paintings_lower_price.describe()

             work_id   sale_price  regular_price
count      58.000000    58.000000       58.00000
mean    42837.724138   185.517241      406.37931
std     59939.637345   237.652425      480.79411
min       404.000000    10.000000       75.00000
25%      7335.000000    30.000000       95.00000
50%     28260.000000    40.000000      125.00000
75%     30947.000000   305.000000      632.50000
max    198417.000000  1025.000000     2235.00000

In [97]:
# 5. Which canvas size costs the most?
#Calculates the area and finds the index of the maximum area,then retrieves the row.
most_expensive_canvas_size = d2.loc[(d2['width'] * d2['height']).idxmax()]

In [98]:
most_expensive_canvas_size

size_id                          8959
width                              89
height                           59.0
label      89" x 59"(226 cm x 150 cm)
Name: 198, dtype: object

In [99]:
# 6. Delete duplicate records from work, product_size, subject, and image_link tables
d7.drop_duplicates(inplace=True)
d5.drop_duplicates(inplace=True)
d6.drop_duplicates(inplace=True)
d8.drop_duplicates(inplace=True)

In [100]:
# 7. Identify the museums with invalid city information in the given dataset
museums_invalid_city = d3[d3['city'].isnull()]

In [101]:
museums_invalid_city

Empty DataFrame
Columns: [museum_id, name, address, city, state, postal, country, phone, url]
Index: []

In [102]:
# 8. Museum_Hours table has 1 invalid entry. Identify it and remove it.
museum_hours_invalid = d4[d4['museum_id'].isnull()]

In [103]:
museum_hours_invalid

Empty DataFrame
Columns: [museum_id, day, open, close]
Index: []

In [104]:
# 9. Fetch the top 10 most famous painting subjects
top_10_subjects = d6['subject'].value_counts().head(10)

In [105]:
top_10_subjects

Portraits              1070
Nude                    525
Landscape Art           495
Rivers/Lakes            480
Flowers                 457
Abstract/Modern Art     399
Still-Life              395
Seascapes               323
Marine Art/Maritime     268
Horses                  265
Name: subject, dtype: int64

In [106]:
# 10. Identify the museums which are open on both Sunday and Monday. Display museum name, city.
museums_open_both_days = d4[d4['day'].isin(['Sunday', 'Monday'])].merge(d3, on='museum_id')[['name', 'city']].drop_duplicates()

In [107]:
museums_open_both_days

                                                 name             city
0                            The Museum of Modern Art         New York
2                   Pushkin State Museum of Fine Arts           Moscow
4                        National Gallery of Victoria        Melbourne
6                             São Paulo Museum of Art        São Paulo
7                          The State Hermitage Museum                2
8                      The Metropolitan Museum of Art         New York
10                                    Museum Folkwang            45128
11                                 Museum of Grenoble            38000
13                    Musée des Beaux-Arts de Quimper            29000
14                        Nelson-Atkins Museum of Art      Kansas City
16                                    Musée du Louvre            75001
18                           National Maritime Museum           London
20                         Museum of Fine Arts Boston           Boston
22                                        Rijksmuseum        Amsterdam
24                                      Israel Museum        Jerusalem
26                                   Kunsthaus Zürich           Zurich
27                            National Gallery of Art       Washington
29                                   National Gallery           London
31                                 Mauritshuis Museum         Den Haag
33                                      Musée d'Orsay            Paris
34                                   The Prado Museum           Madrid
36                              The Barnes Foundation     Philadelphia
38                         Hungarian National Gallery         Budapest
39                            Cleveland Museum Of Art        Cleveland
40                       Museum of Fine Arts, Houston          Houston
41                           The J. Paul Getty Museum      Los Angeles
42                          Thussen-Bornemisza Museum           Madrid
43                                    Van Gogh Museum        Amsterdam
45                            The Phillips Collection       Washington
46                               Toledo Museum of Art           Toledo
47                   Los Angeles County Museum of Art      Los Angeles
49                       Solomon R. Guggenheim Museum         New York
51                                   The Tate Gallery           London
53                         Indianapolis Museum of Art     Indianapolis
54                       Museum of Fine Arts of Nancy            Nancy
56  Fine Arts Museums of San Francisco Legion of H...    San Francisco
57                    Smithsonian American Art Museum       Washington
59                         Philadelphia Museum of Art     Philadelphia
61                       The Art Institute of Chicago          Chicago
63                             Saint Louis Art Museum        St. Louis
64                               Uffizi Gallery Italy          Firenze
65                                Ohara Museum of Art        Kurashiki
66                              Musée Marmottan Monet            Paris
67                                 Walters Art Museum        Baltimore
68                              Kröller-Müller Museum  6731 AW Otterlo
69                                    National Museum          Cardiff
70                             Columbus Museum of Art         Columbus
71                                 Kimbell Art Museum       Fort Worth
72                                 Walker Art Gallery        Liverpool
73     National Museum of Art Architecture and Design             Oslo
74                               Dallas Museum of Art           Dallas
75                                Museum of Fine Arts             Bern
76                                        Army Museum            Paris
78                             Chrysler Museum of Art          Norfolk
79                            National Gallery Prague        Nové Měst
81                                Norton Simon Museum         Pasadena
83                                  Courtauld Gallery            Stran

In [108]:
# 11. How many museums are open every single day?
museums_open_every_day = d4.groupby('museum_id')['day'].nunique()
num_museums_open_every_day = sum(museums_open_every_day == 7)

In [109]:
num_museums_open_every_day

17

In [110]:
# 12. Which are the top 5 most popular museums? (Popularity is defined based on the most number of paintings in a museum)
top_5_popular_museums = d7['museum_id'].value_counts().head(5)

In [111]:
top_5_popular_museums

35.0    939
43.0    452
47.0    423
46.0    375
51.0    350
Name: museum_id, dtype: int64

In [112]:
# 13. Who are the top 5 most popular artists? (Popularity is defined based on the most number of paintings done by an artist)
top_5_popular_artists = d7['artist_id'].value_counts().head(5)

In [113]:
top_5_popular_artists

500    469
550    378
677    308
649    253
559    233
Name: artist_id, dtype: int64

In [114]:
# 14. Display the 3 least popular canvas sizes
least_popular_canvas_sizes = d2['size_id'].value_counts().tail(3)

In [115]:
least_popular_canvas_sizes

3020    1
3024    1
9648    1
Name: size_id, dtype: int64

In [116]:
#15.X

In [117]:
# 16. Which museum has the most number of the most popular painting style?

# Assuming you have a column in the work table that indicates the painting style, let's call it 'style'
most_popular_painting_style = d7.groupby('museum_id')['style'].value_counts().groupby(level=0).idxmax().value_counts().idxmax()

In [118]:
most_popular_painting_style

(30.0, 'Cubism')

In [119]:
# 17. Identify the artists whose paintings are displayed in multiple countries
artists_multiple_countries = d7.merge(d3, on='museum_id').groupby('artist_id')['country'].nunique()
artists_multiple_countries = artists_multiple_countries[artists_multiple_countries > 1]

In [120]:
artists_multiple_countries

artist_id
500    6
501    2
503    2
504    3
505    3
      ..
912    4
913    2
916    4
919    2
920    6
Name: country, Length: 194, dtype: int64

In [121]:
most_museums_country_city = d3.groupby(['country', 'city']).size().idxmax()

In [122]:
#18
most_museums_country_city

('France', 'Paris')

In [123]:
print(d2.columns)

Index(['size_id', 'width', 'height', 'label'], dtype='object')

In [124]:
# 19. Identify the artist and the museum where the most expensive and least expensive painting is placed.

In [125]:
most_expensive_painting

work_id          22890
size_id           4896
sale_price        1115
regular_price     2045
Name: 47091, dtype: object

In [126]:
least_expensive_painting

work_id          31780
size_id             36
sale_price          10
regular_price      125
Name: 220, dtype: object

In [127]:
# 20. Which country has the 5th highest number of paintings?
fifth_highest_painting_country = d3.merge(d7, on='museum_id').groupby('country').size().nlargest(5).index[4]

In [128]:
fifth_highest_painting_country

'Spain'

In [129]:
# 21. Which are the 3 most popular and 3 least popular painting styles?
most_popular_styles = d7['style'].value_counts().head(3)
least_popular_styles = d7['style'].value_counts().tail(3)

In [130]:

most_popular_styles,least_popular_styles

(Impressionism         3078
 Post-Impressionism    1672
 Realism               1179
 Name: style, dtype: int64,
 Avant-Garde     146
 Art Nouveau     108
 Japanese Art     70
 Name: style, dtype: int64)

In [131]:
# 22. Which artist has the most number of Portrait paintings outside the USA?
portrait_paintings_outside_usa = d1[(d1['nationality'] != 'USA') & (d1['style'] == 'Portrait')]

try:
    artist_with_most_portrait_paintings = portrait_paintings_outside_usa['full_name'].value_counts().idxmax()
    print("Artist with the most number of Portrait paintings outside the USA:", artist_with_most_portrait_paintings)
except ValueError:
    print("There are no portrait paintings outside the USA according to the given criteria.")

There are no portrait paintings outside the USA according to the given criteria.